In [10]:
import scanpy as sc
import pandas as pd
import numpy as np
# some standard packages to assist this tutorial
import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc
import anndata as ad
from scipy.sparse import csr_matrix

In [11]:
data_c = pd.read_csv('/data/share/data/data_c_del_rowcol.csv')
data_c.set_index('Gene Name', drop=True, append=False, inplace=True)
data_c = np.log(data_c + 1)
data_t = pd.read_csv('/data/share/data/data_t_del_rowcol.csv')
data_t.set_index('Gene Name', drop=True, append=False, inplace=True)
data_t = np.log(data_t + 1)
print(data_c.shape, data_t.shape)

(27166, 3325) (27166, 3325)

In [12]:
data_c

,wild type_1,wild type_2,wild type_3,wild type_4,wild type_5,wild type_6,wild type_9,wild type_10,wild type_11,wild type_12,...,wild type_3448,wild type_3449,wild type_3450,wild type_3452,wild type_3453,wild type_3454,wild type_3457,wild type_3460,wild type_3461,wild type_3462
Gene Name,,,,,,,,,,,,,,,,,,,,,
0610006L08Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013041,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007381,0.000000,0.000000
0610009B22Rik,0.000000,2.913492,2.868449,4.134545,2.758487,2.758487,2.819805,2.208898,2.899224,3.776115,...,3.240857,3.240857,3.240857,0.420998,2.033064,1.374175,2.633743,2.944785,3.305174,2.657610
0610010F05Rik,1.158592,2.254265,2.254666,1.987259,3.113407,3.113407,2.810784,2.384648,2.433286,2.317089,...,2.415243,2.415243,2.415243,1.555746,1.164711,1.134868,1.411520,2.028959,1.920440,2.347447
0610010K14Rik,0.021912,2.489766,2.757202,3.976702,2.710902,2.710902,2.273515,2.508973,2.053449,4.130148,...,2.337376,2.337376,2.337376,2.372110,4.199490,3.852176,2.431781,2.978761,3.754601,3.030129
0610012G03Rik,1.881002,3.580057,3.381651,3.928268,3.530752,3.530752,2.594292,2.414709,3.427541,2.747287,...,1.855522,1.855522,1.855522,2.377652,2.729656,2.542550,3.864599,4.558817,2.685830,2.846667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zyx,0.680606,5.044731,4.915519,4.743120,5.805014,5.805014,2.438143,3.894719,2.232094,1.780521,...,1.116565,1.116565,1.116565,0.282404,0.901799,2.312540,4.200520,4.486439,5.769363,5.693144
Zzef1,3.044184,2.332872,2.428515,0.995969,1.819270,1.819270,2.248923,2.554291,2.426685,1.965152,...,1.439542,1.439542,1.439542,2.446347,2.448481,2.300919,1.551428,1.614582,1.492638,2.787203
Zzz3,1.539474,2.164096,2.715629,2.099945,2.833406,2.833406,2.553762,2.568593,2.079630,2.602305,...,3.370086,3.370086,3.370086,3.240528,3.301177,2.526913,1.504085,1.858683,2.442616,2.448722
a,4.021251,0.000000,0.000000,0.052822,0.000000,0.000000,0.000000,0.063829,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.059011,0.000000,0.000000,0.000000
ccdc198,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019172,0.369395,0.000000,0.000000,...,0.113714,0.113714,0.113714,0.000000,0.059027,0.000000,0.000000,0.000000,0.000000,0.940870

In [13]:
data_t

,Jagn1_1,Dhcr24_2,Dhcr24_3,Epcam_4,Cdk8_5,Cdk8_6,Irf8_9,Irf8_10,Cybb_11,Rsf1_12,...,Skiv2l_3448,Skiv2l_3449,Skiv2l_3450,Mir155_3452,Mir155_3453,Mir155_3454,Ogt_3457,Ogt_3460,Zfp281_3461,Mir379_3462
Gene Name,,,,,,,,,,,,,,,,,,,,,
0610006L08Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.023214,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
0610009B22Rik,0.465922,2.667185,2.767940,4.047388,3.202122,3.013076,2.348409,2.399388,2.603772,3.688244,...,3.299716,3.106673,2.923832,1.454949,2.178326,1.172836,2.724081,3.122672,3.261322,2.797590
0610010F05Rik,1.061476,2.277352,2.256249,2.056162,3.347701,3.389847,2.771389,2.558135,2.392684,1.767090,...,2.454328,2.159812,1.997685,1.428997,1.341852,1.184417,1.029446,1.715162,1.815667,2.250776
0610010K14Rik,0.085466,2.187100,2.120589,3.867641,3.532715,3.485501,2.171422,2.659355,3.274711,3.351224,...,2.744637,2.523585,2.344390,3.754913,4.172966,4.204823,2.196904,2.630918,3.764078,3.110431
0610012G03Rik,1.819875,3.235712,3.172365,4.154650,3.461723,3.382530,2.616128,2.587746,3.409223,2.855982,...,1.856255,1.684385,1.501133,2.341563,2.367386,2.631343,4.215603,4.796260,2.971629,3.021435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zyx,0.702267,4.949367,4.971191,4.296021,6.009609,6.089398,2.756438,3.681975,2.296041,2.627065,...,1.342694,1.550269,1.807148,0.956938,1.468531,2.182169,4.323976,4.631068,5.386790,5.800631
Zzef1,3.352746,2.545458,2.594460,0.871516,1.839374,1.709890,2.720019,2.572207,2.540594,1.621944,...,1.431166,1.624044,1.827708,2.302477,2.454332,2.214372,1.561730,1.691757,1.741939,2.908661
Zzz3,1.605719,2.506131,2.378713,2.070835,2.951227,2.930097,2.625304,2.676841,2.049000,2.669302,...,3.307726,3.142549,4.141743,3.122573,3.322017,2.399647,1.602390,1.940587,2.624870,2.366809
a,2.696737,0.000000,0.000000,0.064446,0.000000,0.000000,0.000000,0.072125,0.000000,0.000000,...,0.000000,0.141444,0.046129,0.000000,0.000000,0.000000,0.000000,0.021146,0.000000,0.000000
ccdc198,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.292006,0.568274,0.073458,0.039955,...,0.046424,0.016911,0.036865,0.000000,0.084747,0.000000,0.001874,0.002157,0.000000,0.836929

In [14]:
columns_name = list(data_t.columns)
print(len(columns_name))
data_c.columns = columns_name
# 将要敲除的基因值置为 0
data_c_copy = data_c.copy()
for i in data_c.columns:
    ko_name = i.split('_')[0]
    ko_name = ko_name.split('/')[0]
    data_c.at[ko_name, i] = 0

3325

In [15]:
data_c.shape

(27210, 3325)

In [16]:
data_c

,Jagn1_1,Dhcr24_2,Dhcr24_3,Epcam_4,Cdk8_5,Cdk8_6,Irf8_9,Irf8_10,Cybb_11,Rsf1_12,...,Skiv2l_3448,Skiv2l_3449,Skiv2l_3450,Mir155_3452,Mir155_3453,Mir155_3454,Ogt_3457,Ogt_3460,Zfp281_3461,Mir379_3462
Gene Name,,,,,,,,,,,,,,,,,,,,,
0610006L08Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013041,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007381,0.000000,0.000000
0610009B22Rik,0.000000,2.913492,2.868449,4.134545,2.758487,2.758487,2.819805,2.208898,2.899224,3.776115,...,3.240857,3.240857,3.240857,0.420998,2.033064,1.374175,2.633743,2.944785,3.305174,2.657610
0610010F05Rik,1.158592,2.254265,2.254666,1.987259,3.113407,3.113407,2.810784,2.384648,2.433286,2.317089,...,2.415243,2.415243,2.415243,1.555746,1.164711,1.134868,1.411520,2.028959,1.920440,2.347447
0610010K14Rik,0.021912,2.489766,2.757202,3.976702,2.710902,2.710902,2.273515,2.508973,2.053449,4.130148,...,2.337376,2.337376,2.337376,2.372110,4.199490,3.852176,2.431781,2.978761,3.754601,3.030129
0610012G03Rik,1.881002,3.580057,3.381651,3.928268,3.530752,3.530752,2.594292,2.414709,3.427541,2.747287,...,1.855522,1.855522,1.855522,2.377652,2.729656,2.542550,3.864599,4.558817,2.685830,2.846667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mir322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mir183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mir181a-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gm6421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tcra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
data_c = data_c.drop(columns=['-----_707'])
data_t = data_t.drop(columns=['-----_707'])
columns_name = list(data_t.columns)

In [18]:
data_test_c1 = pd.read_csv('./data_c_choose_3000.csv')

data_test_c1.set_index('Gene Name', drop=True, append=False, inplace=True)
name_test = list(data_test_c1.index)

data_c=data_c.loc[name_test]

data_t=data_t.loc[name_test]
name_drop = data_t.index
data_c = data_c.values.T
data_t = data_t.values.T

In [19]:
data_c.shape, data_t.shape

((3324, 3072), (3324, 3072))

In [20]:
# knock data c
print(len(columns_name))
obs = pd.DataFrame()
obs['batch'] = np.random.choice(['0', '1'], data_c.shape[0]) # 样本数，每个样本观测信息
obs['knock_gene'] = columns_name
obs['knock_or_not'] = 'yes'
var_names = name_test
n_vars = len(var_names)         # 输出大小为genes数目
var = pd.DataFrame(index=var_names)
print(len(columns_name)) # 敲除的基因list
new_data_c = ad.AnnData(data_c,obs=obs,var=var)

3324
3324

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [21]:
# unknock data t
obs = pd.DataFrame()
obs['batch'] = np.random.choice(['0', '1'], data_t.shape[0]) # 样本数，每个样本观测信息
obs['knock_gene'] = columns_name
obs['knock_or_not'] = 'no'
var_names = name_test
n_vars = len(var_names)         # 输出大小为genes数目
var = pd.DataFrame(index=var_names)
print(len(columns_name)) # 敲除的基因list
new_data_t = ad.AnnData(data_t,obs=obs,var=var)

3324

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [22]:
new_data_c.to_df()

,Hnrnpll,Hspa9,Igf2bp2,Imp3,Larp1,Larp4,Lgals3,Lsm1,Lsm14a,Lsm3,...,Zscan29,Zscan4-ps1,Zscan4-ps2,Zscan4-ps3,Zscan4b,Zscan4c,Zscan4d,Zscan4e,Zscan4f,Zscan5b
0,0.569787,3.256832,0.251553,4.740725,2.455521,2.537594,0.000000,0.758312,2.736561,3.737134,...,1.085141,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,3.134559,3.910700,1.185976,3.628490,3.058187,1.861516,7.231031,1.862180,3.902553,3.403257,...,2.368666,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,3.112283,3.889291,1.105397,3.488988,3.047795,2.413923,7.128831,1.703701,3.967476,3.202591,...,2.441869,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,3.511050,4.673506,0.449867,4.695636,2.919392,2.660630,3.594945,3.336009,3.484109,5.684031,...,1.528076,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,4.074482,6.035937,3.488898,4.263327,3.854100,3.534744,4.240838,2.860605,4.298375,4.637973,...,1.949010,0.0,0.0,0.0,0.0,0.007874,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3319,1.249053,5.700394,0.000000,3.708689,3.821038,2.146053,1.904056,1.761895,4.744205,4.101300,...,2.066048,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3320,2.572244,4.350497,2.738217,3.298422,3.498926,2.134670,5.879609,1.869314,3.614873,3.391303,...,1.880486,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3321,3.333441,4.885010,2.515829,3.848580,3.309425,2.652983,7.914034,2.106465,3.628738,3.791722,...,1.523018,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3322,3.929998,5.997680,3.111327,4.061772,4.510201,3.589258,4.710266,2.926989,3.962370,4.618504,...,1.724499,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3323,3.251037,5.216639,3.000413,3.341263,3.547565,2.541565,2.807863,2.114867,3.916701,3.765563,...,1.600382,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [23]:
new_data_t.to_df()

,Hnrnpll,Hspa9,Igf2bp2,Imp3,Larp1,Larp4,Lgals3,Lsm1,Lsm14a,Lsm3,...,Zscan29,Zscan4-ps1,Zscan4-ps2,Zscan4-ps3,Zscan4b,Zscan4c,Zscan4d,Zscan4e,Zscan4f,Zscan5b
0,0.700315,3.988474,0.183818,4.936464,2.526417,2.623999,0.000000,1.006218,2.748409,3.499748,...,1.336762,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
1,3.096880,3.824309,1.252462,3.591532,3.081105,2.449253,6.961417,1.678718,3.785726,2.999847,...,2.459119,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
2,3.154039,3.867253,1.063963,3.550862,3.027438,2.371869,7.044977,1.822219,3.851456,3.094337,...,2.528043,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3,3.660577,5.140118,0.508509,4.892746,3.136171,2.778263,1.303222,3.354764,3.503367,5.686224,...,1.407123,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
4,3.925710,5.969414,3.440687,3.995621,3.966354,3.687376,3.721078,2.813180,4.332323,4.784412,...,1.603850,0.0,0.010536,0.020651,0.0,0.0,0.084552,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3319,1.267729,5.718397,0.000000,3.632468,3.817850,2.252917,2.082614,1.470151,4.580839,3.951860,...,2.242313,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3320,2.521689,4.495480,3.386434,3.025454,3.660287,2.246498,6.516849,1.736649,3.636871,3.412981,...,2.000932,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3321,3.306292,4.758996,2.833915,3.473663,3.291074,2.670448,8.101326,1.993747,3.611969,3.565884,...,1.683268,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3322,4.164594,5.503739,3.963904,4.460119,4.450643,3.428715,5.010887,2.537302,4.336258,4.244070,...,1.751923,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3323,3.185096,5.178130,2.963961,3.466732,3.402378,2.340601,3.008121,2.253393,3.717321,3.862441,...,1.425063,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0

In [24]:
new_adatas = [new_data_t, new_data_c]
new_adatas = ad.concat(new_adatas)
new_adatas.to_df()

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

,Hnrnpll,Hspa9,Igf2bp2,Imp3,Larp1,Larp4,Lgals3,Lsm1,Lsm14a,Lsm3,...,Zscan29,Zscan4-ps1,Zscan4-ps2,Zscan4-ps3,Zscan4b,Zscan4c,Zscan4d,Zscan4e,Zscan4f,Zscan5b
0,0.700315,3.988474,0.183818,4.936464,2.526417,2.623999,0.000000,1.006218,2.748409,3.499748,...,1.336762,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
1,3.096880,3.824309,1.252462,3.591532,3.081105,2.449253,6.961417,1.678718,3.785726,2.999847,...,2.459119,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
2,3.154039,3.867253,1.063963,3.550862,3.027438,2.371869,7.044977,1.822219,3.851456,3.094337,...,2.528043,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3,3.660577,5.140118,0.508509,4.892746,3.136171,2.778263,1.303222,3.354764,3.503367,5.686224,...,1.407123,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
4,3.925710,5.969414,3.440687,3.995621,3.966354,3.687376,3.721078,2.813180,4.332323,4.784412,...,1.603850,0.0,0.010536,0.020651,0.0,0.0,0.084552,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3319,1.249053,5.700394,0.000000,3.708689,3.821038,2.146053,1.904056,1.761895,4.744205,4.101300,...,2.066048,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3320,2.572244,4.350497,2.738217,3.298422,3.498926,2.134670,5.879609,1.869314,3.614873,3.391303,...,1.880486,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3321,3.333441,4.885010,2.515829,3.848580,3.309425,2.652983,7.914034,2.106465,3.628738,3.791722,...,1.523018,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3322,3.929998,5.997680,3.111327,4.061772,4.510201,3.589258,4.710266,2.926989,3.962370,4.618504,...,1.724499,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
3323,3.251037,5.216639,3.000413,3.341263,3.547565,2.541565,2.807863,2.114867,3.916701,3.765563,...,1.600382,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0

In [25]:
new_adatas.obs['split'] = 'train'
new_adatas.obs

     batch   knock_gene knock_or_not  split
0        1      Jagn1_1           no  train
1        1     Dhcr24_2           no  train
2        0     Dhcr24_3           no  train
3        1      Epcam_4           no  train
4        0       Cdk8_5           no  train
...    ...          ...          ...    ...
3319     0  Mir155_3454          yes  train
3320     1     Ogt_3457          yes  train
3321     0     Ogt_3460          yes  train
3322     0  Zfp281_3461          yes  train
3323     0  Mir379_3462          yes  train

[6648 rows x 4 columns]

In [35]:
data_test_c1 = pd.read_csv('./data_c_choose_3000.csv')
data_test_c1.set_index('Gene Name', drop=True, append=False, inplace=True)

data_test_c1

,Kdm1a_1,Smyd5_2,Dnmt3a_3,Dnmt3a_4,Dnmt3b_5,Dnmt3b_6,Ino80_7,Evx1_8,Hoxd12_9
Gene Name,,,,,,,,,
Hnrnpll,2.361763,3.473567,3.537143,3.793344,3.801299,3.885268,3.560269,2.821351,2.663640
Hspa9,4.871223,5.521318,4.985968,5.080704,5.843260,5.742072,4.951774,4.700342,4.997567
Igf2bp2,0.377074,3.620242,0.494236,0.304561,3.741159,3.575843,3.891384,2.700467,3.258663
Imp3,4.482229,3.865845,4.021733,4.312796,4.274449,3.977438,3.426256,3.411614,4.871664
Larp1,3.478740,3.840728,3.679902,3.723516,4.069477,4.909152,3.952610,4.268351,3.605145
...,...,...,...,...,...,...,...,...,...
Zscan4c,0.000000,0.979192,0.000000,0.000000,0.000000,0.000000,0.058244,0.133236,0.781963
Zscan4d,0.000000,1.444619,0.000000,0.000000,0.000000,0.000000,0.036717,0.075808,0.658283
Zscan4e,0.000000,1.282271,0.000000,0.000000,0.000000,0.000000,0.080222,0.088611,0.000000
Zscan4f,0.000000,0.712328,0.000000,0.000000,0.000000,0.000000,0.000000,0.073897,0.412710
Zscan5b,0.000000,1.033689,0.000000,0.000000,0.407489,0.000000,0.056580,0.000000,1.027804

In [46]:
# unknock data t
columns_name_test = list(data_test_c1.columns)
data_test_c11 = data_test_c1.values.T
obs_test = pd.DataFrame()
obs_test['batch'] = np.random.choice(['0', '1'], data_test_c11.shape[0]) # 样本数，每个样本观测信息
obs_test['knock_gene'] = columns_name_test
obs_test['knock_or_not'] = 'yes'
obs_test['split'] = 'test'
var_names = name_test
n_vars = len(var_names)         # 输出大小为genes数目
print(n_vars)
var_test = pd.DataFrame(index=var_names)
print(len(columns_name_test)) # 敲除的基因list

# new_data_t.write('./new_data_c')

3072
9

In [47]:
new_data_test_c1 = ad.AnnData(data_test_c11,obs=obs_test,var=var_test)

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [50]:
new_data_test_c1.obs

  batch knock_gene knock_or_not split
0     1    Kdm1a_1          yes  test
1     1    Smyd5_2          yes  test
2     0   Dnmt3a_3          yes  test
3     1   Dnmt3a_4          yes  test
4     0   Dnmt3b_5          yes  test
5     1   Dnmt3b_6          yes  test
6     1    Ino80_7          yes  test
7     0     Evx1_8          yes  test
8     1   Hoxd12_9          yes  test

In [49]:
# unknock data t
columns_name_test = list(data_test_c1.columns)
data_test_c11 = data_test_c1.values.T
obs_test = pd.DataFrame()
obs_test['batch'] = np.random.choice(['0', '1'], data_test_c11.shape[0]) # 样本数，每个样本观测信息
obs_test['knock_gene'] = columns_name_test
obs_test['knock_or_not'] = 'yes'
obs_test['split'] = 'ood'
var_names = name_test
n_vars = len(var_names)         # 输出大小为genes数目
print(n_vars)
var_test = pd.DataFrame(index=var_names)
print(len(columns_name_test)) # 敲除的基因list

# new_data_t.write('./new_data_c')

new_data_test_c2 = ad.AnnData(data_test_c11,obs=obs_test,var=var_test)

3072
9

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:117: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [51]:
new_data_test_c2.obs

  batch knock_gene knock_or_not split
0     1    Kdm1a_1          yes   ood
1     0    Smyd5_2          yes   ood
2     0   Dnmt3a_3          yes   ood
3     1   Dnmt3a_4          yes   ood
4     1   Dnmt3b_5          yes   ood
5     1   Dnmt3b_6          yes   ood
6     0    Ino80_7          yes   ood
7     1     Evx1_8          yes   ood
8     0   Hoxd12_9          yes   ood

In [52]:
# 合并训练集和测试集 
new_data_all = [new_adatas, new_data_test_c1, new_data_test_c2]
new_data_all = ad.concat(new_data_all)
new_data_all.obs['control'] = 1
new_data_all.obs

new_data_all.obs['split'] = new_data_all.obs['split'].astype('category')
new_data_all.obs['knock_gene'] = new_data_all.obs['knock_gene'].astype('category')
new_data_all.obs['knock_or_not'] = new_data_all.obs['knock_or_not'].astype('category')
new_data_all.obs['control'] = new_data_all.obs['control'].astype('category')

new_data_all.obs['knock_gene'].cat.categories
new_data_all.obs['knock_or_not'].cat.categories
new_data_all.obs['split'].cat.categories

/home/cnic02/miniconda3/envs/cb/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

Index(['ood', 'test', 'train'], dtype='object')

In [53]:
new_data_all.to_df()

,Hnrnpll,Hspa9,Igf2bp2,Imp3,Larp1,Larp4,Lgals3,Lsm1,Lsm14a,Lsm3,...,Zscan29,Zscan4-ps1,Zscan4-ps2,Zscan4-ps3,Zscan4b,Zscan4c,Zscan4d,Zscan4e,Zscan4f,Zscan5b
0,0.700315,3.988474,0.183818,4.936464,2.526417,2.623999,0.000000,1.006218,2.748409,3.499748,...,1.336762,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
1,3.096880,3.824309,1.252462,3.591532,3.081105,2.449253,6.961417,1.678718,3.785726,2.999847,...,2.459119,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
2,3.154039,3.867253,1.063963,3.550862,3.027438,2.371869,7.044977,1.822219,3.851456,3.094337,...,2.528043,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
3,3.660577,5.140118,0.508509,4.892746,3.136171,2.778263,1.303222,3.354764,3.503367,5.686224,...,1.407123,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
4,3.925710,5.969414,3.440687,3.995621,3.966354,3.687376,3.721078,2.813180,4.332323,4.784412,...,1.603850,0.000000,0.010536,0.020651,0.0,0.000000,0.084552,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,3.801299,5.843260,3.741159,4.274449,4.069477,3.528722,4.610158,3.055685,4.208447,5.420596,...,1.585602,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.407489
5,3.885268,5.742072,3.575843,3.977438,4.909152,3.544987,0.000000,3.059707,4.249671,5.060699,...,1.568989,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
6,3.560269,4.951774,3.891384,3.426256,3.952610,3.056942,2.779677,1.913038,3.916031,3.724683,...,1.642379,0.048887,0.077894,0.027334,0.0,0.058244,0.036717,0.080222,0.000000,0.056580
7,2.821351,4.700342,2.700467,3.411614,4.268351,2.599738,4.253296,2.134492,3.293097,3.932155,...,1.314861,0.085950,0.038690,0.042428,0.0,0.133236,0.075808,0.088611,0.073897,0.000000
8,2.663640,4.997567,3.258663,4.871664,3.605145,2.169392,2.703749,2.981209,3.076805,5.963236,...,0.763867,0.363924,0.071426,0.368954,0.0,0.781963,0.658283,0.000000,0.412710,1.027804

In [54]:
new_data_all.write('./bulk_3072_train_test_CPA.h5ad')

In [62]:
output_data = pd.read_csv('/data/share/cnic02/projects/perturb_cwt/result100_2_3000_tf_ko_div0_312_ko_200_del0.csv')

In [63]:
output_data.shape

(3072, 10)

In [64]:
output_data

,Gene Name,0,1,2,3,4,5,6,7,8
0,Hnrnpll,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Hspa9,5.430887,5.562448,4.643332,4.954725,5.903327,5.699311,4.896484,4.831459,5.242384
2,Igf2bp2,0.596275,3.483797,0.762671,1.066739,3.504312,3.451672,3.922924,3.562689,2.881712
3,Imp3,3.967688,3.868679,3.844951,3.922436,3.811528,3.893404,3.399512,3.650591,4.577901
4,Larp1,3.116681,4.022244,3.762424,3.812984,4.097397,4.344134,3.869970,4.139788,3.248435
...,...,...,...,...,...,...,...,...,...,...
3067,Zscan4c,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3068,Zscan4d,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3069,Zscan4e,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3070,Zscan4f,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3071,Zscan5b,0.000000,0.608731,0.000000,0.000000,0.468884,0.000000,0.000000,0.000000,0.929882

In [59]:
out_cpa = pd.read_csv('/data/share/cnic02/projects/perturb_cwt/bulk_3072_test_CPA_tran.csv')
out_cpa.shape

(3072, 10)